/**
 * SAAT Configuration Loader
 * Loads and validates configuration from saat.config.ts
 */

import { existsSync } from 'fs';
import { resolve } from 'path';
import type { SaatConfig, RuleInfo } from './config-types.js';

/**
 * Rule metadata for reference
 */
const WCAG_RULES_METADATA: Record<string, RuleInfo> = {
  '1.1.1': {
    id: '1.1.1',
    name: 'Non-text Content',
    level: 'A',
    description: 'All non-text content that is presented to the user has a text alternative that serves the equivalent purpose',
  },
  '1.3.1': {
    id: '1.3.1',
    name: 'Info and Relationships',
    level: 'A',
    description: 'Information, structure, and relationships conveyed through presentation can be programmatically determined or are available in text',
  },
  '1.3.2': {
    id: '1.3.2',
    name: 'Meaningful Sequence',
    level: 'A',
    description: 'When the sequence in which content is presented affects its meaning, a correct reading sequence can be programmatically determined',
  },
  '1.4.1': {
    id: '1.4.1',
    name: 'Use of Color',
    level: 'A',
    description: 'Color is not used as the only visual means of conveying information, indicating an action, prompting a response, or distinguishing a visual element',
  },
  '2.1.1': {
    id: '2.1.1',
    name: 'Keyboard Access',
    level: 'A',
    description: 'All functionality of the content is operable through a keyboard interface without requiring specific timings for individual keystrokes',
  },
  '2.2.1': {
    id: '2.2.1',
    name: 'Timing',
    level: 'A',
    description: 'For each time limit that is set by the content, at least one of the following is true: the user is allowed to turn off the time limit',
  },
  '2.4.1': {
    id: '2.4.1',
    name: 'Bypass Blocks',
    level: 'A',
    description: 'A mechanism is available to bypass blocks of content that are repeated on multiple Web pages',
  },
  '2.4.3': {
    id: '2.4.3',
    name: 'Focus Order',
    level: 'A',
    description: 'If a Web page can be navigated sequentially and the navigation sequences affect the meaning or operation, focusable components receive focus in an order that preserves meaning and operability',
  },
  '2.4.4': {
    id: '2.4.4',
    name: 'Link Purpose',
    level: 'A',
    description: 'The purpose of each link can be determined from the link text alone or from the link text together with its programmatically determined link context',
  },
  '2.5.1': {
    id: '2.5.1',
    name: 'Pointer Gestures',
    level: 'A',
    description: 'All functionality that uses multipoint or path-based gestures for operation can be operated with a single pointer without a path-based gesture',
  },
  '3.1.1': {
    id: '3.1.1',
    name: 'Language of Page',
    level: 'A',
    description: 'The default human language of each Web page can be programmatically determined',
  },
  '3.2.4': {
    id: '3.2.4',
    name: 'Consistent Identification',
    level: 'AA',
    description: 'Components that have the same functionality are identified consistently',
  },
  '3.3.1': {
    id: '3.3.1',
    name: 'Error Identification',
    level: 'A',
    description: 'If an input error is detected automatically, the item that is in error is identified and the error is described to the user in text',
  },
  '3.3.2': {
    id: '3.3.2',
    name: 'Labels or Instructions',
    level: 'A',
    description: 'Labels or instructions are provided when content requires user input',
  },
  '4.1.2': {
    id: '4.1.2',
    name: 'Name, Role, Value',
    level: 'A',
    description: 'For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined',
  },
  '4.1.3': {
    id: '4.1.3',
    name: 'Status Messages',
    level: 'AA',
    description: 'In content implemented using markup languages, status messages can be programmatically determined through role or properties such that they can be presented to the user by assistive technologies without receiving focus',
  },
};

/**
 * Load default configuration
 */
export function getDefaultConfig(): SaatConfig {
  const allRuleIds: string[] = Object.keys(WCAG_RULES_METADATA);
  return {
    componentsDir: 'front/src/components',
    outputDir: 'front/a11y/reports',
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    rules: allRuleIds as any as SaatConfig['rules'],
    minConformity: 85,
    generateBadge: true,
    output: {
      json: true,
      markdown: true,
      rulesSummary: true,
      prettyJson: true,
    },
    logging: {
      level: 'normal',
      timing: false,
    },
  };
}

/**
 * Dynamically load configuration from saat.config.ts
 */
export async function loadConfig(configPath?: string): Promise<SaatConfig> {
  try {
    const resolvedPath = configPath ? resolve(configPath) : resolve(process.cwd(), 'saat.config.ts');

    if (!existsSync(resolvedPath)) {
      console.warn(`⚠️  Config file not found at ${resolvedPath}, using defaults`);
      return getDefaultConfig();
    }

    // Use dynamic import for ESM module
    const configModule = await import(`file://${resolvedPath}`);
    const config = configModule.default as SaatConfig;

    // Validate configuration
    validateConfig(config);

    return config;
  } catch (error) {
    console.warn(`⚠️  Failed to load config: ${error instanceof Error ? error.message : 'Unknown error'}`);
    return getDefaultConfig();
  }
}

/**
 * Validate configuration
 */
function validateConfig(config: SaatConfig): void {
  if (!config.componentsDir) {
    throw new Error('componentsDir is required in configuration');
  }

  if (!config.outputDir) {
    throw new Error('outputDir is required in configuration');
  }

  if (!config.rules || config.rules.length === 0) {
    throw new Error('rules array is required and must not be empty');
  }

  if (config.minConformity < 0 || config.minConformity > 100) {
    throw new Error('minConformity must be between 0 and 100');
  }
}

/**
 * Export metadata for reference
 */
export function getAvailableRules(): RuleInfo[] {
  return Object.values(WCAG_RULES_METADATA);
}
